server:
  port: 8181
spring:
  datasource:
    name: test
    url: jdbc:mysql://rm-uf63067964237hb6j2o.mysql.rds.aliyuncs.com:3306/tb_db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC&useAffectedRows=true
    username: web_user
    password: web2020!
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml  # a注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.studentcard.demo.entity  # 注意：对应实体类的路径